name: Publish Docker image for tag

on:
  push:
    tags:
      # Since this action pushes just a tagged image it is only active on tags. We exclude `-dev` tags.
      - 'v*'
      - '!v*-dev'

env:
  TEST_TAG: zeek:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Get Version
        id: version
        run: echo "::set-output name=RELEASE_VERSION::$(cat VERSION)"
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          load: true
      - name: Run tests
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
            image: ${{ env.TEST_TAG }}
            config: docker/container-structure-test.yaml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            zeekurity/zeek:${{ steps.version.outputs.RELEASE_VERSION }}
